import Head from 'next/head'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Fisioterapia Melissa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-screen">
        <Header />
        <div className="flex flex-col items-center w-full h-full py-6 font-mono bg-red-300 text-white">
          <h1 className="text-6xl font-bold">Bienvenido a Fisiomel</h1>
          <p className="mt-3 text-2xl">
            Dejanos ayudarte a mejorar tu calidad de vida
          </p>
          <section className="bg-white dark:bg-gray-900 my-4 hero h-2/3 flex items-center justify-center bg-cover bg-center-center bg-no-repeat">
            <div className="max-w-screen-xl px-4 py-8 mx-auto text-center lg:py-16 lg:px-12">
              <h1 className="mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Tu cuerpo es tu compañero de vida cuídalo, escúchalo y atiéndelo.</h1>
            </div>
          </section>

        </div>
        <Footer />
      </main>
    </>
  )
}
